//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlantInfo
    {
        public string PlantID { get; set; }
        public string PlantName { get; set; }
        public string PalntAddress { get; set; }
        public string IsDefault { get; set; }
    }
}
