//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receive
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Receive()
        {
            this.ReceiveDetails = new HashSet<ReceiveDetail>();
        }
    
        public long Id { get; set; }
        public Nullable<int> ReceiveSourceId { get; set; }
        public string ReceiveReferenceNo { get; set; }
        public Nullable<System.DateTime> ReceiveReferenceDate { get; set; }
        public string SupplierId { get; set; }
        public string GRNNo { get; set; }
        public System.DateTime GRNDate { get; set; }
        public string ChallanNo { get; set; }
        public System.DateTime ChallanDate { get; set; }
        public string VATChallanNo { get; set; }
        public Nullable<System.DateTime> VATChallanDate { get; set; }
        public string ReceiveText { get; set; }
        public string PlantId { get; set; }
        public Nullable<int> FiscalYear { get; set; }
        public Nullable<byte> IsPosted { get; set; }
        public string PostBy { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public Nullable<byte> IsPaid { get; set; }
        public string PaidUserId { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public string EntryBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string EditBy { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiveDetail> ReceiveDetails { get; set; }
        public virtual TransactionSource TransactionSource { get; set; }
    }
}
