//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiveDetail
    {
        public int Id { get; set; }
        public Nullable<int> ReceiveId { get; set; }
        public string OrderNo { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> OrderQuantity { get; set; }
        public Nullable<double> VAT { get; set; }
        public Nullable<int> ReceivedQuantity { get; set; }
    
        public virtual Received Received { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
