//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiveDetail
    {
        public long Id { get; set; }
        public long ReceiveId { get; set; }
        public string MaterialCode { get; set; }
        public Nullable<decimal> OrderQuantity { get; set; }
        public Nullable<decimal> ChallanQuantity { get; set; }
        public Nullable<decimal> ReceivedQuantity { get; set; }
        public string DetailUnit { get; set; }
        public Nullable<decimal> DetailQuantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> VatPercent { get; set; }
        public Nullable<decimal> VatAmount { get; set; }
        public string BatchNo { get; set; }
        public string ManufacturerId { get; set; }
        public string ManufacturerLotNo { get; set; }
        public Nullable<decimal> LotQuantity { get; set; }
        public Nullable<int> NoOfPack { get; set; }
        public Nullable<byte> IsQCReleased { get; set; }
        public Nullable<decimal> RestrictedQuantity { get; set; }
    
        public virtual Receive Receive { get; set; }
    }
}
